# Generated by Django 2.1.7 on 2019-10-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='queue',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='position',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='user',
        ),
    ]
